### PR TITLE
Tarot reversed long

### PR DESCRIPTION
**Pull request by h-anjru**
Brick by brick I am adding to the tarot deck, giving each card a long-form description for how to interpret it when it is dealt in the reversed position. Once the deck is amended, I will add the new description to the `>tarot card` embed.

### CODE REVIEW

**Comment by kaylynn234** [comment]
As a nit, it may be good to do a formatting pass on the YAML once all the descriptions are done. I believe there's.. _something_ in the YAML spec to multi-line strings nicely but I'm not sure what it is - I'll have to do some research in that regard.

**Comment by williammck** [comment]
> I believe there's.. _something_ in the YAML spec to multi-line strings nicely

https://yaml-multiline.info/

**Comment by h-anjru** [comment]
I know I *can* format the YAML to enforce a char limit, but *should* I? This YAML is 95% prose and 5% "code," and enforcing a char limit as though the YAML is code would be enforcing a rule for consistency's sake, or so it seems to me. IDEs and the Github website handle word wrap just fine, and the work of formatting the YAML after the fact to a 120-char limit feels pointless.

**Comment by williammck** [comment]
> I know I _can_ format the YAML to enforce a char limit, but _should_ I? This YAML is 95% prose and 5% "code," and enforcing a char limit as though the YAML is code would be enforcing a rule for consistency's sake, or so it seems to me. IDEs and the Github website handle word wrap just fine, and the work of formatting the YAML after the fact to a 120-char limit feels pointless.

Fair question, and at this point we're bikeshedding, but I'll answer anyway.

Here's a couple reasons why I like splitting it out over multiple lines (usually demarcating around punctuation):
* I personally keep word wrap off globally as a consistency thing. I don't typically like word wrap, even in blocks of prose that's inside code. (e.g. a paragraph on an HTML page) Just how my brain works, idk.
* If we change the text in the future (fixing typos, etc), since it would be split among multiple lines, the diff would be far easier to read and actually see what's changed.

But I'm not going to block your PR on it. 🤷🏻‍♂️

**Comment by h-anjru** [comment]
Yoodith wrote their long descriptions for the cards in like three days. I needed three months!

**Review by williammck — APPROVED** [review]
code looks good. trusting you with the card definitions. 😆

**Pull request merged**
