### PR TITLE
Fix bubblewrap's ability to choose a random emoji

### PR DESCRIPTION
**Pull request by h-anjru**
Last one today, I promise! Simple fix.

### CODE REVIEW

**Comment by kaylynn234** [comment]
This may not do what you'd like. Some emoji span multiple codepoints and this could end up accidentally picking one singular codepoint that's invalid on its own.

**Comment by h-anjru** [comment]
You are right, but remember that the emoji list is very limited. I chose emojis originally for the list based on simple handling. I don't think any of the emojis in the emoji list span multiple codepoints.

**Review by williammck — APPROVED** [review]
IIRC I removed any emoji with multiple codepoints from our list, so we should be okay.

**Comment by williammck** [comment]
> IIRC I removed any emoji with multiple codepoints from our list, so we should be okay.

yep. https://github.com/crimsobot/crimsoBOT/pull/84

**Pull request merged**
